### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by at-wat** [seqsense/aports-ros-experimental#123]

**Comment by at-wat** [comment]
# py3 specific (?) errors:
## message_filters
```
ERROR: test_approx (test_approxsync.TestApproxSync)
```

```
Traceback (most recent call last):
  File "/home/builder/aports/ros-py3/melodic/message_filters/apk-build-temporary/src/message_filters/test/test_approxsync.py", line 96, in test_approx
    m1.signalMessage(msg)
  File "<string>", line 57, in signalMessage
  File "<string>", line 282, in add
  File "<string>", line 282, in <listcomp>
TypeError: 'zip' object is not subscriptable
```
## actionlib
Tests in actionlib looks calling python script directly. Some of the scripts run in python2 and cause errors.

## smach_ros
actionlib related test failed.

## tf
`tf.rosunit-test_broadcaster_reciept` failed.

## interactive_markers
`testserver_test` failed.

## cv_bridge (*py3 incompatible)
The code seems not supporting python3 (e.g. `TypeError: a bytes-like object is required, not 'str'`)

## camera_calibration_parsers
Type error.

## camera_info_manager
Test timed-out.

## urdfdom_py (*py3 incompatible)
```
TabError: inconsistent use of tabs and spaces in indentation
```

## image_proc
Test timed-out.

## python_orocos_kdl (*py3 incompatible)
`python_orocos_kdl` forces python version to 2.
This causes another failures on depending packages.

## tf2_geometry_msgs
Code using `python_orocos_kdl` doesn't work due to missing py3 support.

**Comment by at-wat** [comment]
done
