### ISSUE TITLE
rosdep failing to initialise

### ISSUE THREAD

**Issue by MarkHedleyJones** [seqsense/aports-ros-experimental#81]
Steps to reproduce:

```
FROM alpineros/alpine-ros:kinetic-bare
RUN apk add ros-kinetic-ros-core
RUN rosdep init
RUN rosdep update
```
Fails with
```
Traceback (most recent call last):
  File "/usr/bin/rosdep", line 3, in <module>
    from rosdep2.main import rosdep_main
  File "/usr/lib/python2.7/site-packages/rosdep2/__init__.py", line 45, in <module>
    from .lookup import RosdepDefinition, RosdepView, RosdepLookup, \
  File "/usr/lib/python2.7/site-packages/rosdep2/lookup.py", line 44, in <module>
    from .sources_list import SourcesListLoader
  File "/usr/lib/python2.7/site-packages/rosdep2/sources_list.py", line 49, in <module>
    from .gbpdistro_support import get_gbprepo_as_rosdep_data, download_gbpdistro_as_rosdep_data
  File "/usr/lib/python2.7/site-packages/rosdep2/gbpdistro_support.py", line 18, in <module>
    from .platforms.debian import APT_INSTALLER
  File "/usr/lib/python2.7/site-packages/rosdep2/platforms/debian.py", line 34, in <module>
    from rospkg.os_detect import OS_DEBIAN, OS_LINARO, OS_UBUNTU, OS_ELEMENTARY, OS_MX, OsDetect, read_os_release
ImportError: cannot import name OS_MX
```

**Comment by at-wat** [comment]
rospkg seems needed to be upgraded.

**Comment by at-wat** [comment]
OS_MX was introduced by rospkg 1.1.8.

**Comment by shsrinivgit** [comment]
Try:
sudo apt-get install python-rospkg
